Repository TeamFogFog/FogFog-iOS, pull requests merged in 2022-11, with the labels that each got.

#4 [#3] 프로젝트 초기 세팅
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  FogFog-iOS/FogFog-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  FogFog-iOS/FogFog-iOS/App/AppDelegate.swift
  FogFog-iOS/FogFog-iOS/App/SceneDelegate.swift
  FogFog-iOS/FogFog-iOS/Models/.gitkeep
  FogFog-iOS/FogFog-iOS/Presentation/BottomDetailView/BottomDetailViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/BottomDetailView/SplashViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/SideBar/SideBarViewController.swift
  FogFog-iOS/FogFog-iOS/Resources/Base.lproj/LaunchScreen.storyboard
  FogFog-iOS/FogFog-iOS/Resources/Colors/Color.xcassets/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Fonts/.gitkeep
  FogFog-iOS/FogFog-iOS/Resources/Image/Asset.xcassets/AccentColor.colorset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Asset.xcassets/AppIcon.appiconset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Asset.xcassets/Contents.json
  FogFog-iOS/FogFog-iOS/Supports/Info.plist
  FogFog-iOS/FogFog-iOS/Utils/Analytics/.gitkeep
  FogFog-iOS/FogFog-iOS/Utils/Base/BaseViewController.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/.gitkeep
  FogFog-iOS/FogFog-iOS/Utils/Logging/.gitkeep
  FogFog-iOS/FogFog-iOS/Utils/Logging/Logger.swift
  FogFog-iOS/FogFog-iOS/Utils/UIComponents/.gitkeep
  FogFog-iOS/FogFog-iOSTests/FogFog_iOSTests.swift
  FogFog-iOS/FogFog-iOSUITests/FogFog_iOSUITests.swift
  FogFog-iOS/FogFog-iOSUITests/FogFog_iOSUITestsLaunchTests.swift
Labels: Config, D-2

#7 [#6] Font, Image 추가
  .gitignore
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/Resources/Fonts/FogFont.swift
  FogFog-iOS/FogFog-iOS/Resources/Fonts/Pretendard-Black.otf
  FogFog-iOS/FogFog-iOS/Resources/Fonts/Pretendard-Bold.otf
  FogFog-iOS/FogFog-iOS/Resources/Fonts/Pretendard-ExtraBold.otf
  FogFog-iOS/FogFog-iOS/Resources/Fonts/Pretendard-ExtraLight.otf
  FogFog-iOS/FogFog-iOS/Resources/Fonts/Pretendard-Light.otf
  FogFog-iOS/FogFog-iOS/Resources/Fonts/Pretendard-Medium.otf
  FogFog-iOS/FogFog-iOS/Resources/Fonts/Pretendard-Regular.otf
  FogFog-iOS/FogFog-iOS/Resources/Fonts/Pretendard-SemiBold.otf
  FogFog-iOS/FogFog-iOS/Resources/Fonts/Pretendard-Thin.otf
  FogFog-iOS/FogFog-iOS/Resources/Image/FogImage.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_fogfog.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_fogfog.imageset/ic_fogfog.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_fogfog.imageset/ic_fogfog@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_fogfog.imageset/ic_fogfog@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_ham.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_ham.imageset/ic_ham.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_ham.imageset/ic_ham@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_ham.imageset/ic_ham@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_location.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_location.imageset/loca.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_location.imageset/loca@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_location.imageset/loca@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_minus.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_minus.imageset/ic_minus.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_minus.imageset/ic_minus@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_minus.imageset/ic_minus@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_plus.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_plus.imageset/ic_plus.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_plus.imageset/ic_plus@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_plus.imageset/ic_plus@3x.png
  FogFog-iOS/FogFog-iOS/Supports/Info.plist
  FogFog-iOS/FogFog-iOS/Utils/Extension/UIFont + Extension.swift
Labels: Config, D-2

#9 [#8] 라이브러리 설치 (SPM 및 cocoapods)
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FogFog-iOS/FogFog-iOS.xcworkspace/contents.xcworkspacedata
  FogFog-iOS/FogFog-iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  FogFog-iOS/FogFog-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FogFog-iOS/Podfile
  FogFog-iOS/Podfile.lock
Labels: Config, D-2, 😁승짠

#11 [#10] MapView UI 작업
  .gitignore
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/App/AppDelegate.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/NavigationView.swift
  FogFog-iOS/FogFog-iOS/Supports/Info.plist
  FogFog-iOS/FogFog-iOS/Utils/Base/BaseViewController.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/Bundle + Extension.swift
Labels: Config, D-2

#13 [#5] Danger를 이용한 SwiftLint 설정
  .github/workflows/action.yml
  Dangerfile
  FogFog-iOS/.swiftlint.yml
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/Presentation/BottomDetailView/BottomDetailViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/BottomDetailView/SplashViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/SideBar/SideBarViewController.swift
  FogFog-iOS/FogFog-iOS/Resources/Fonts/FogFont.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/FogImage.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/UIFont + Extension.swift
  FogFog-iOS/Podfile.lock
  Gemfile
  Gemfile.lock
Labels: Config, ☀️ 태끼, D-2, CI/CD

#15 [#12] Coordinator 설계 및 세팅
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/App/SceneDelegate.swift
  FogFog-iOS/FogFog-iOS/Presentation/Common/Coordinator/Delegate/CoordinatorFinishDelegate.swift
  FogFog-iOS/FogFog-iOS/Presentation/Common/Coordinator/ImplAppCoordinator.swift
  FogFog-iOS/FogFog-iOS/Presentation/Common/Coordinator/Protocol/AppCoordinator.swift
  FogFog-iOS/FogFog-iOS/Presentation/Common/Coordinator/Protocol/Coordinator.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/Coordinator/ImplLoginCoordinator.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/Coordinator/Protocol/LoginCoordinator.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/LoginViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/LoginViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/Coordinator/ImplMapCoordinator.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/Coordinator/Protocol/MapCoordinator.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
  FogFog-iOS/FogFog-iOS/Utils/Contstant/CoordinatorCase.swift
Labels: Config, 😁승짠

#16 [#14] 로그인 뷰 UI 구성
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Sign/SignInViewController.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/FogImage.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/appleLogo.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/appleLogo.imageset/appleLogo.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/appleLogo.imageset/appleLogo@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/appleLogo.imageset/appleLogo@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnCheck.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnCheck.imageset/btnCheck.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnCheck.imageset/btnCheck@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnCheck.imageset/btnCheck@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/kakaoLogol.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/kakaoLogol.imageset/kakaoLogol.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/kakaoLogol.imageset/kakaoLogol@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/kakaoLogol.imageset/kakaoLogol@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/mapImage.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/mapImage.imageset/mapImage.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/mapImage.imageset/mapImage@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/mapImage.imageset/mapImage@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/speechBubbleSmall.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/speechBubbleSmall.imageset/speechBubbleSmall.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/speechBubbleSmall.imageset/speechBubbleSmall@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/speechBubbleSmall.imageset/speechBubbleSmall@3x.png
  FogFog-iOS/FogFog-iOS/Utils/Base/BaseViewController.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/Adjusted + Extension.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/UIColor + Extension.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/UIView + Extension.swift
Labels: 🫠 은주, UI

#20 [#18] BottomDetailView 레이아웃 구현
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FogFog-iOS/FogFog-iOS/Models/Place/SmokePlace.swift
  FogFog-iOS/FogFog-iOS/Presentation/BottomDetailView/BottomDetailViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/BottomDetailView/View/BottomDetailRootView.swift
  FogFog-iOS/FogFog-iOS/Presentation/BottomDetailView/View/BottomDetailViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/BottomDetailView/ViewModel/BottomDetailViewModel.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/FogImage.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/fluentLocation16Filled.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/fluentLocation16Filled.imageset/fluentLocation16Filled.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/fluentLocation16Filled.imageset/fluentLocation16Filled@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/fluentLocation16Filled.imageset/fluentLocation16Filled@3x.png
  FogFog-iOS/FogFog-iOS/Utils/Base/BaseView.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/UIColor + Extension.swift
Labels: ☀️ 태끼, D-2, UI

#21 [#17] 메인 뷰 사이드 바 UI 구성
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/Presentation/Common/Protocol/ViewModelType.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/LoginViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/NavigationView.swift
  FogFog-iOS/FogFog-iOS/Presentation/SideBar/SideBarView.swift
  FogFog-iOS/FogFog-iOS/Presentation/Sign/SignInViewController.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/FogImage.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnMap.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnMap.imageset/btnMap.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnMap.imageset/btnMap@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnMap.imageset/btnMap@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnNotice.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnNotice.imageset/btnNotice.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnNotice.imageset/btnNotice@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnNotice.imageset/btnNotice@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnSet.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnSet.imageset/btnSet.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnSet.imageset/btnSet@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnSet.imageset/btnSet@3x.png
  FogFog-iOS/FogFog-iOS/Utils/Extension/UIColor + Extension.swift
Labels: 🫠 은주, UI

#24 [#23] 길 찾기 팝업 구현
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/App/SceneDelegate.swift
  FogFog-iOS/FogFog-iOS/Presentation/BottomDetailView/View/BottomDetailRootView.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/FogImage.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnX.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnX.imageset/btnX.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnX.imageset/btnX@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnX.imageset/btnX@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/iconPopupMap.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/iconPopupMap.imageset/map.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/iconPopupMap.imageset/map@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/iconPopupMap.imageset/map@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/speechBubbleBig.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/speechBubbleBig.imageset/speech bubble_big.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/speechBubbleBig.imageset/speech bubble_big@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/speechBubbleBig.imageset/speech bubble_big@3x.png
  FogFog-iOS/FogFog-iOS/Utils/Base/BaseViewController.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/UIColor + Extension.swift
  FogFog-iOS/FogFog-iOS/Utils/UIComponents/.gitkeep
  FogFog-iOS/FogFog-iOS/Utils/UIComponents/FogButton/FogButton.swift
  FogFog-iOS/FogFog-iOS/Utils/UIComponents/FogButton/FogButtonStyle.swift
  FogFog-iOS/FogFog-iOS/Utils/UIComponents/RoadPopUp/ExMapType.swift
  FogFog-iOS/FogFog-iOS/Utils/UIComponents/RoadPopUp/RoadPopUpView.swift
  FogFog-iOS/FogFog-iOS/Utils/UIComponents/RoadPopUp/RoadPopUpViewController.swift
  FogFog-iOS/FogFog-iOS/Utils/UIComponents/RoadPopUp/RoadPopUpViewModel.swift
Labels: ☀️ 태끼, D-2, UI

#27 [#26] action.yml 파일 환경변수명 수정
  .github/workflows/action.yml
Labels: CI/CD, Fix, D-0

#25 [#22] 닉네임 설정 뷰 UI 구성
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FogFog-iOS/FogFog-iOS/Presentation/Login/ViewController/LoginViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/ViewController/MakeNicknameViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/ViewModel/MakeNicknameViewModel.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/FogImage.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnBack.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnBack.imageset/btnBack.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnBack.imageset/btnBack@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/btnBack.imageset/btnBack@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/iconDeletetext.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/iconDeletetext.imageset/iconDeletetext.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/iconDeletetext.imageset/iconDeletetext@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/iconDeletetext.imageset/iconDeletetext@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/inputTextIocnNotice.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/inputTextIocnNotice.imageset/inputTextIocnNotice.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/inputTextIocnNotice.imageset/inputTextIocnNotice@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/inputTextIocnNotice.imageset/inputTextIocnNotice@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/wordmark.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/wordmark.imageset/wordmark.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/wordmark.imageset/wordmark@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/wordmark.imageset/wordmark@3x.png
  FogFog-iOS/FogFog-iOS/Utils/Extension/UIColor + Extension.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/UILabel + Extension.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/UITextField + Extension.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/UIView + Extension.swift
  FogFog-iOS/FogFog-iOS/Utils/UIComponents/FogNavigationView.swift
  FogFog-iOS/FogFog-iOS/Utils/UIComponents/FogTextField.swift
Labels: 🫠 은주, UI
