Repository TeamFogFog/FogFog-iOS, pull requests merged in 2023-10, with the labels that each got.

#77 [#76] 스플래시 화면 추가 및 다크모드 대응
  FogFog-iOS/FogFog-iOS/Presentation/SideBar/SideBarView.swift
  FogFog-iOS/FogFog-iOS/Resources/Base.lproj/LaunchScreen.storyboard
  FogFog-iOS/FogFog-iOS/Resources/Image/FogImage.swift
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/fogfog_logo.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/fogfog_logo.imageset/fogfog_logo.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/fogfog_logo.imageset/fogfog_logo@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/fogfog_logo.imageset/fogfog_logo@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_fogfog.imageset/ic_fogfog.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_fogfog.imageset/ic_fogfog@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/ic_fogfog.imageset/ic_fogfog@3x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/invalidName.imageset/Contents.json
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/invalidName.imageset/invalidName.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/invalidName.imageset/invalidName@2x.png
  FogFog-iOS/FogFog-iOS/Resources/Image/Image.xcassets/invalidName.imageset/invalidName@3x.png
  FogFog-iOS/FogFog-iOS/Supports/Info.plist
Labels: Config, D-2, 🫠 은주, UI

#78 [#75] 앱 첫 실행 시 키체인 정보 초기화
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/App/AppDelegate.swift
  FogFog-iOS/FogFog-iOS/Networking/APIServices/AuthAPIService.swift
  FogFog-iOS/FogFog-iOS/Networking/APIServices/QuitAPIService.swift
  FogFog-iOS/FogFog-iOS/Presentation/ExternalMap/ExternalMapModalViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/ViewModel/MakeNicknameViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/Setting/Cell/SettingNicknameTableViewCell.swift
  FogFog-iOS/FogFog-iOS/Presentation/Setting/ViewModel/SettingViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/SideBar/SideBarView.swift
  FogFog-iOS/FogFog-iOS/Utils/Class/Keychain.swift
  FogFog-iOS/FogFog-iOS/Utils/Contstant/UserDefaultsKey.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/UserDefaults + Extension.swift
  FogFog-iOS/FogFog-iOS/Utils/Wrapper/UserDefault.swift
Labels: enhancement, D-2, 🫠 은주, refactor

#82 [#80] 네비게이션 컨트롤러 Pop Gesture 추가
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/App/SceneDelegate.swift
  FogFog-iOS/FogFog-iOS/Presentation/Common/Coordinator/Protocol/Coordinator.swift
  FogFog-iOS/FogFog-iOS/Utils/Base/BaseNavigationController.swift
  FogFog-iOS/FogFog-iOS/Utils/Base/BaseViewController.swift
Labels: ☀️ 태끼, UI
