Repository TeamFogFog/FogFog-iOS, pull requests merged in 2023-07, with the labels that each got.

#57 [#47] 애플 인증 플로우 구현
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/Manager/AppleLogin/ASAuthorizationControllerProxy.swift
  FogFog-iOS/FogFog-iOS/Manager/AppleLogin/AppleLoginManager.swift
  FogFog-iOS/FogFog-iOS/Manager/AppleLoginManager.swift
  FogFog-iOS/FogFog-iOS/Models/User/AppleUserModel.swift
  FogFog-iOS/FogFog-iOS/OAuth/AppleOAuthService.swift
  FogFog-iOS/FogFog-iOS/OAuth/OAuthProviderType.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/ViewController/LoginViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/ViewModel/LoginViewModel.swift
Labels: D-2, 🫠 은주, Network, 인증, 애플 로그인, Auth, refactor

#60 [#44] 지도 권한 로직 개선
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/Presentation/Map/Coordinator/DefaultMapCoordinator.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/DefaultLoactionService.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/LocationService.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/NavigationView.swift
Labels: D-2, 😁승짠, Fix, refactor

#61 [#58] Danger 설정 제거
  .github/workflows/action.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: Config
