Repository TeamFogFog/FogFog-iOS, pull requests merged in 2023-09, with the labels that each got.

#68 [#67] 로그인 플로우에서 설정 뷰로 화면전환 되지 않는 문제 해결
  FogFog-iOS/FogFog-iOS/Presentation/Login/Coordinator/DefaultLoginCoordinator.swift
  FogFog-iOS/FogFog-iOS/Presentation/Login/ViewModel/MakeNicknameViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Map/MapViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/Setting/Cell/SettingNicknameTableViewCell.swift
  FogFog-iOS/FogFog-iOS/Presentation/Setting/Coordinator/DefaultSettingCoordinator.swift
  FogFog-iOS/FogFog-iOS/Presentation/Setting/ViewController/SettingViewController.swift
  FogFog-iOS/FogFog-iOS/Presentation/Setting/ViewModel/SettingViewModel.swift
  FogFog-iOS/FogFog-iOS/Presentation/SideBar/SideBarView.swift
  FogFog-iOS/FogFog-iOS/Utils/Extension/Reactive + Extension.swift
Labels: bug, D-2, 🫠 은주, refactor

#72 [#65] MapAPIService 구현
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/Models/Map/Coordinates.swift
  FogFog-iOS/FogFog-iOS/Models/Map/SmokingAreaEntity.swift
  FogFog-iOS/FogFog-iOS/Networking/APIServices/MapAPIService.swift
  FogFog-iOS/FogFog-iOS/Networking/APIs/MapAPI.swift
Labels: 지도

#73 [#55] 회원탈퇴 기능 구현
  FogFog-iOS/FogFog-iOS.xcodeproj/project.pbxproj
  FogFog-iOS/FogFog-iOS/Networking/APIServices/QuitAPIService.swift
  FogFog-iOS/FogFog-iOS/Networking/APIs/AuthAPI.swift
Labels: 회원탈퇴
